spring:
  application:
    name: teste-livraria
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: false
server:
  port: 8080

