create table TB_LIVROS
(
    idt_livro      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    des_titulo     CHARACTER VARYING(1000000000) not null,
    des_autor      CHARACTER VARYING(1000000000) not null,
    des_descricao  CHARACTER VARYING(1000000000) not null,
    dat_lancamento DATE                          not null,
    cod_isbn       CHARACTER VARYING(1000000000) not null
);